title: Teleoperación móvil-manipulador

description: Manual académico y de réplica para proyecto universitario de robótica teleoperada con realidad mixta.
theme: just-the-docs
baseurl: "/teleop-mobile-manipulator"
url: https://sebas30073007.github.io/teleop-mobile-manipulator

aux_links:
  Repositorio del proyecto: https://github.com/sebas30073007/teleop-mobile-manipulator
  English: /teleop-mobile-manipulator/en/

defaults:
  - scope:
      path: ""
    values:
      layout: default
